[config]
reload_apps = false

[templates.waybar]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.rofi]
input_path = "~/.config/matugen/templates/wifi.rasi"
output_path = "~/.config/rofi/wifi.rasi"

[templates.bluetooth]
input_path = "~/.config/matugen/templates/bluetooth.rasi"
output_path = "~/.config/rofi/bluetooth.rasi"

[templates.control-center]
input_path = "~/.config/matugen/templates/control-center.rasi"
output_path = "~/.config/rofi/control-center.rasi"
