$foreground = {{colors.on_surface.default.rgba}}
$foreground_dim = {{colors.on_surface_variant.default.rgba}}
$panel = {{colors.surface.default.rgba | set_alpha: 0.70}}
$accent = {{colors.primary.default.rgba}}
$border = {{colors.primary.default.rgba | set_alpha: 0.60}}
$error = {{colors.error.default.rgba}}
